### ISSUE TITLE
Inlier indices should be size_t not char

### ISSUE THREAD

**Issue by RReverser** [vlarsson/PoseLib#55]
Currently inliers are represented via `std::vector<char>` that stores indices. This can be problematic for large datasets, as `char` is only limited to maximum value of `127` on common platforms, and anything larger will go via silent number truncation, potentially leading to all sorts of bugs when attempting to use that index again.

Internally all indices are correctly represented via `size_t`, and that's what inliers vector should use as well.

**Comment by tsattler** [comment]
The `std::vector<char>` returned do not store indices. Rather, they contain one entry for each data point that specifies whether this data point is an inlier to the model or not. Since each entry only needs to store a binary decision (inlier or not), the maximum size of `char` is not an issue here. One could also use a `std::vector<bool>` here, which would make this behavior more explicit but comes with the issues / problems that using `std::vector<bool>` brings with it.

**Comment by RReverser** [comment]
Oh. Good point, thanks, I mixed it up when looking at the code.

> but comes with the issues / problems that using `std::vector<bool>` brings with it

What kind of problems do you envision in this context? Having a compact bit vector seems useful for this use-case.

**Comment by RReverser** [comment]
(I'll close this issue anyway as that discussion is not directly relevant, thanks again.)

**Comment by tsattler** [comment]
The issue with `std::vector<bool>` is that it might not be compatible with all functionality from the C++ standard template library: https://en.cppreference.com/w/cpp/container/vector_bool

**Comment by RReverser** [comment]
Sure, but for most use-cases I can think of, it should be fine (you rarely need more than iteration or getting presence by index) and for the rest developer can still convert to `vector<char>` or whatever.
